### ISSUE TITLE
Uncaught Exception becomes two occurences in Rollbar app

### ISSUE THREAD

**Issue by hngl** [rollbar/rollbar-php-symfony-bundle#36]
When using a basic Symfony 4 setup with the setup of the bundle as described in the [Rollbar Symfony docs](https://docs.rollbar.com/docs/symfony), one Exception thrown becomes 2 lines in the occurrences table.

trace.exception.message | custom.channel | custom.datetime | custom.level | custom.payload.body.trace_chain
------------------------ | ---------------- | ----------------- | ------------- | --------------------------
Example msg | app | 1539001010 | error | [{"frames":...
Example msg | request | 1539001009 | critical | (empty)

### Setup

config/bundles.php
```php
<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
   /* ... */
   
	// RollbarBundle must be included _after_ MonologBundle
    Rollbar\Symfony\RollbarBundle\RollbarBundle::class => ['prod' => true],
];
```

config/packages/prod/rollbar.yaml
```yaml
rollbar:
  enabled: true
  access_token: '%env(ROLLBAR_TOKEN)%'
  environment: '%env(APP_HOST)%'
```

config/packages/monolog.yaml
```yaml
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error # log all errors with status code >= 400
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, deduplicated]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'noreply@example.org'
            to_email:   '%env(SERVER_ADMIN)%'
            subject:    '%%message%%'
            level:      notice
            formatter:  monolog.formatter.html
            content_type: text/html

```

config/packages/prod/monolog.yaml
```yaml
monolog:
  handlers:
    # This appends `rollbar` to the environment-independent list of handlers
    rollbar:
      type: service
      id: Rollbar\Monolog\Handler\RollbarHandler
```
