### ISSUE TITLE
Why the minimum level of reporting is set to ERROR?

### ISSUE THREAD

**Issue by jantenuccigsbla** [rollbar/rollbar-php-symfony-bundle#57]
Hi All!
I need to send Debug & Info messages through this bundle (Its possible to do it with the SDK of rollbar)

But in the RollBarHandlerFactory of this bundle set the minimum level in ERROR. It means that i cant send any event below error level (ie info / debug levels)
So $logger->info('INFO MESSAGE') wont work :S

See the code
`/**
     * Create RollbarHandler
     *
     * @return RollbarHandler
     */
    public function createRollbarHandler()
    {
        return new RollbarHandler(Rollbar::logger(), LogLevel::ERROR);
    }
`

Any suggestions?
Thanks a lot

**Comment by javer** [comment]
Yes, it's easy:
1. Drop dependency on this bundle and use only `composer require rollbar/rollbar:^2.0`
2. Add to `config/services.yaml`:
```yaml
parameters:
    rollbar.config:
        access_token: 'your_access_token'
        environment: 'your_environment'
        code_version: 'your_code_version'
        allow_exec: false
        exception_sample_rates:
            Symfony\Component\HttpKernel\Exception\HttpException: 0
        # any other options available in https://docs.rollbar.com/docs/php-configuration-reference

services:
    App\Logger\Handler\RollbarHandlerFactory:
        $config: '%rollbar.config%'

    Rollbar\Monolog\Handler\RollbarHandler:
        factory: ['@App\Logger\Handler\RollbarHandlerFactory', createRollbarHandler]
        tags:
            - { name: monolog.logger, channel: rollbar }
```
3. Create `App\Logger\Handler\RollbarHandlerFactory` class:
```php
<?php

namespace App\Logger\Handler;

use Psr\Log\LogLevel;
use Rollbar\Monolog\Handler\RollbarHandler;
use Rollbar\Rollbar;

class RollbarHandlerFactory
{
    public function __construct(array $config)
    {
        Rollbar::init($config, false, false, false);
    }

    public function createRollbarHandler(): RollbarHandler
    {
        return new RollbarHandler(Rollbar::logger(), LogLevel::INFO);
    }
}
```
4. Enjoy and don't wait for years until new features from Rollbar library itself appear in this bundle.
